#178 Getting Started: revision on pre-deployment prerequisites
railwayapp/docs pull request #179
Opened 2022-11-26 06:24 UTC by stormwild

2022-12-08 18:42 UTC, ndneighbor approved these changes
D'oh! Good catch.

2023-01-27 09:04 UTC, ndneighbor approved these changes

2023-04-25 10:41 UTC, half0wl approved these changes

2023-04-25 10:46 UTC, half0wl commented
@stormwild Thanks for the PR! Apologies for the late response here - must've gotten lost in an ocean of things, sorry 'bout that.

This looks good to go! Could you resolve the conflicts so we can merge this in?

2023-04-25 14:07 UTC, stormwild commented
> @stormwild Thanks for the PR! Apologies for the late response here - must've gotten lost in an ocean of things, sorry 'bout that.
> 
> This looks good to go! Could you resolve the conflicts so we can merge this in?

@half0wl PR updated with latest from upstream main

2023-04-26 16:51 UTC, half0wl requested changes
@stormwild thank you! Requesting one minor change that I didn't notice until reading this in context, sorry :-)

2023-04-26 16:51 UTC, half0wl commented on src/docs/getting-started.md
> +Once you are done, save the file, then commit and push to your repo. In the next step, we will show you how easy it is to deploy your changes.
```suggestion
Once you are done, save the file. If you're in a Git repository, you should also commit and push to your repository. In the next step, we will show you how easy it is to deploy your changes.
```

2023-04-28 20:19 UTC, ndneighbor commented
Committed the suggested changes on Alexander's behalf! Merging! Cheers :)

2023-04-28 21:09 UTC, half0wl approved these changes
Thanks @stormwild & @ndneighbor!

2023-04-28 21:09 UTC, merged